tasks:
- init: echo 'init script' # runs during prebuild
  command: echo 'start script'
vscode:
  extensions:
    - mechatroner.rainbow-csv@1.3.1:MGIjKVd23K6AiUfh4hYKNw==
    - ms-vscode.csharp@1.21.9:4NByVUcknHkm8M71U1BkDQ==
image:
  file: .gitpod.Dockerfile
